### ISSUE TITLE
Create a .env file

### ISSUE THREAD

**Issue by amitkparekh** [Aye-saac/website#1]
To avoid any issues when building the website, a .env file needs setting up to make local development and production deployment easier. 

Apparently this is [already available in CRA](https://create-react-app.dev/docs/adding-custom-environment-variables/) so should be an easy fix. 

https://github.com/Aye-saac/website/blob/6cfa158679ae2359b0510eb31981a249aa190f81/src/Helpers/submitQuestion/submitQuestion.ts#L53

**Comment by noeRls** [comment]
fixed in #2
